"use client";

import { useQuery } from "@tanstack/react-query";
import { Activity, CircleDollarSign, ServerCog } from "lucide-react";
import { api } from "@/lib/api";
import type { Workspace } from "@/lib/types";

interface CostSummary { providerKey:string; estimatedUsd:string; actualUsd:string; events:number }
interface CostEvent { id:string; providerKey:string; modelKey:string; estimatedUsd:string; actualUsd?:string|null; occurredAt:string }
export function CostDashboard(){const workspaces=useQuery({queryKey:["workspaces"],queryFn:()=>api<Workspace[]>("/workspaces")});const workspace=workspaces.data?.find(item=>item.role==="owner");const summary=useQuery({queryKey:["cost-summary",workspace?.id],queryFn:()=>api<CostSummary[]>(`/costs/summary?workspaceId=${workspace!.id}`),enabled:Boolean(workspace)});const events=useQuery({queryKey:["cost-events",workspace?.id],queryFn:()=>api<CostEvent[]>(`/costs/events?workspaceId=${workspace!.id}`),enabled:Boolean(workspace)});const total=summary.data?.reduce((sum,row)=>sum+Number(row.actualUsd),0)??0;return <main className="frame-dashboard"><header className="frame-page-header"><div><p className="eyebrow">Operational telemetry</p><h1>Cost observatory.</h1></div></header><section className="cost-stats"><article><CircleDollarSign/><span>Observed spend</span><strong>${total.toFixed(4)}</strong></article><article><Activity/><span>Provider events</span><strong>{summary.data?.reduce((sum,row)=>sum+row.events,0)??0}</strong></article><article><ServerCog/><span>Active providers</span><strong>{summary.data?.length??0}</strong></article></section><section className="cost-table"><header><h2>Latest provider events</h2><span>No credits or billing limits are applied.</span></header>{events.isError?<p className="form-error">Only workspace owners can view cost telemetry.</p>:events.data?.length?<table><thead><tr><th>Provider</th><th>Model</th><th>Estimated</th><th>Actual</th><th>Time</th></tr></thead><tbody>{events.data.map(event=><tr key={event.id}><td>{event.providerKey}</td><td>{event.modelKey}</td><td>${Number(event.estimatedUsd).toFixed(5)}</td><td>{event.actualUsd?`$${Number(event.actualUsd).toFixed(5)}`:"Pending"}</td><td>{new Date(event.occurredAt).toLocaleString()}</td></tr>)}</tbody></table>:<div className="empty-state"><Activity/><h2>No costs recorded.</h2><p>Generation and rendering activity will appear here.</p></div>}</section></main>}
